version: "3.8"

services:
  php-apache:
    image: php:8.1-apache
    container_name: php-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 010203
      MYSQL_DATABASE: siaka
      MYSQL_USER: adm
      MYSQL_PASSWORD: 010203
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 010203
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: always

volumes:
  db_data:
